# Generated by Django 3.0.3 on 2020-02-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvreview',
            name='seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
